### ISSUE TITLE
Weibo cannot handle two URL callback (/connect & /signin)

### ISSUE THREAD

**Issue by ipeisong** [Orange-OpenSource/spring-social-weibo#4]
Sina API only allow one fixed callback URL. I set it to /connect and it works, but when try go sign in with this module, the error occurs again: (error:redirect_uri_mismatch)

But I think this is a big issue of Sina API, is it possible to provide a customized controller to combine the two URLs? Thanks.

**Comment by dvergnes** [comment]
You are right, I have already spotted this issue. But the thing is the spring weibo extension is not the place to fix this. I did not take time to submit an issue on Spring social. I think ConnectController, ProviderSignInController and ConnectSupport should be redesigned to support this use case. Currently, because a lot of methods are private it will probably become really ugly (duplicating code) to implement this. I suggest you submit one issue on https://github.com/SpringSource/spring-social. BTW, it seems to me this issue is really similar to ours https://github.com/SpringSource/spring-social/pull/10. Thank you for your interest please keep me informed about this

**Comment by ipeisong** [comment]
Sorry about this issue:
1. sina API got 2 options: binding domain or not
2. if domain is not bound, a fixed URL is necessary for callback
3. if domain is bound, all URLs from this domain are valid

My fault is that I didn't bind domain, now it is working, thanks for help.
